CREATE TABLE IF NOT EXISTS PRODUCTS(
	ID VARCHAR(25) PRIMARY KEY,
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(250),
	UNIT_PRICE DECIMAL,
	MANUFACTURER VARCHAR(50),
	CATEGORY VARCHAR(50), 
	`CONDITION` VARCHAR(50),
	UNITS_IN_STOCK BIGINT,
	UNITS_IN_ORDER BIGINT,
	DISCONTINUED BOOLEAN
);

CREATE TABLE IF NOT EXISTS CART (
	ID VARCHAR(50) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS CART_ITEM (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	PRODUCT_ID VARCHAR(25),
	CART_ID VARCHAR(50),
	QUANTITY BIGINT,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID), 
	FOREIGN KEY (CART_ID) REFERENCES CART(ID)
);

